### ISSUE TITLE
New Features, Know Bugs and TODO List 

### ISSUE THREAD

**Issue by BIGWangYuDong** [BIGWangYuDong/lqit#30]
If you want any new features or found any bugs in the LQIT repo, please leave message under this issue
## New Features

- [ ] UIEC^2Net
- [ ] UWCNN
- [ ] DUIENet (WaterNet)
- [ ] UColor

## Known Bugs

- [ ] ...

## To-Do List

- [ ] Support Feishu(飞书) robot
- [ ] Avoid Dependency on MMEval
- [ ] Addressing Hardcoding in COCOEval within MMDet (can create a PR in mmdet)
- [ ]
